// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asana-clone-app/ent/deletedprojecttask"
	"asana-clone-app/ent/project"
	"asana-clone-app/ent/schema/ulid"
	"asana-clone-app/ent/task"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DeletedProjectTask is the model entity for the DeletedProjectTask schema.
type DeletedProjectTask struct {
	config `json:"-"`
	// ID of the ent.
	ID ulid.ID `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID ulid.ID `json:"project_id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID ulid.ID `json:"task_id,omitempty"`
	// ProjectTaskSectionID holds the value of the "project_task_section_id" field.
	ProjectTaskSectionID ulid.ID `json:"project_task_section_id,omitempty"`
	// ProjectTaskID holds the value of the "project_task_id" field.
	ProjectTaskID ulid.ID `json:"project_task_id,omitempty"`
	// ProjectTaskCreatedAt holds the value of the "project_task_created_at" field.
	ProjectTaskCreatedAt time.Time `json:"project_task_created_at,omitempty"`
	// ProjectTaskUpdatedAt holds the value of the "project_task_updated_at" field.
	ProjectTaskUpdatedAt time.Time `json:"project_task_updated_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeletedProjectTaskQuery when eager-loading is set.
	Edges        DeletedProjectTaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeletedProjectTaskEdges holds the relations/edges for other nodes in the graph.
type DeletedProjectTaskEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeletedProjectTaskEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeletedProjectTaskEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeletedProjectTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deletedprojecttask.FieldProjectTaskCreatedAt, deletedprojecttask.FieldProjectTaskUpdatedAt, deletedprojecttask.FieldCreatedAt, deletedprojecttask.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case deletedprojecttask.FieldID, deletedprojecttask.FieldProjectID, deletedprojecttask.FieldTaskID, deletedprojecttask.FieldProjectTaskSectionID, deletedprojecttask.FieldProjectTaskID:
			values[i] = new(ulid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeletedProjectTask fields.
func (_m *DeletedProjectTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deletedprojecttask.FieldID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case deletedprojecttask.FieldProjectID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case deletedprojecttask.FieldTaskID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				_m.TaskID = *value
			}
		case deletedprojecttask.FieldProjectTaskSectionID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field project_task_section_id", values[i])
			} else if value != nil {
				_m.ProjectTaskSectionID = *value
			}
		case deletedprojecttask.FieldProjectTaskID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field project_task_id", values[i])
			} else if value != nil {
				_m.ProjectTaskID = *value
			}
		case deletedprojecttask.FieldProjectTaskCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field project_task_created_at", values[i])
			} else if value.Valid {
				_m.ProjectTaskCreatedAt = value.Time
			}
		case deletedprojecttask.FieldProjectTaskUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field project_task_updated_at", values[i])
			} else if value.Valid {
				_m.ProjectTaskUpdatedAt = value.Time
			}
		case deletedprojecttask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case deletedprojecttask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeletedProjectTask.
// This includes values selected through modifiers, order, etc.
func (_m *DeletedProjectTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the DeletedProjectTask entity.
func (_m *DeletedProjectTask) QueryProject() *ProjectQuery {
	return NewDeletedProjectTaskClient(_m.config).QueryProject(_m)
}

// QueryTask queries the "task" edge of the DeletedProjectTask entity.
func (_m *DeletedProjectTask) QueryTask() *TaskQuery {
	return NewDeletedProjectTaskClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this DeletedProjectTask.
// Note that you need to call DeletedProjectTask.Unwrap() before calling this method if this DeletedProjectTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeletedProjectTask) Update() *DeletedProjectTaskUpdateOne {
	return NewDeletedProjectTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeletedProjectTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeletedProjectTask) Unwrap() *DeletedProjectTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeletedProjectTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeletedProjectTask) String() string {
	var builder strings.Builder
	builder.WriteString("DeletedProjectTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("project_task_section_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectTaskSectionID))
	builder.WriteString(", ")
	builder.WriteString("project_task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectTaskID))
	builder.WriteString(", ")
	builder.WriteString("project_task_created_at=")
	builder.WriteString(_m.ProjectTaskCreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("project_task_updated_at=")
	builder.WriteString(_m.ProjectTaskUpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeletedProjectTasks is a parsable slice of DeletedProjectTask.
type DeletedProjectTasks []*DeletedProjectTask
